package br.com.brawbrawlbd.model;

public enum Legends {
	BODVAR,CASSIDY,ORION,LORD_VRAXX,GNASH,QUEEN_NAI,HATTORI,SIR_HOLLAND,SCARLET,THATCH,ADA,SENTINEL,LUCIEN,TEROS,
	BRYNN,ASURI,BARRAZA,EMBER,AZOTH,KOJI,ULGRIM,DIANA,JHALA,KOR,WU_SHANG,VAL,RAGNIR,CROSS,MIRAGE,NIX,MORDEX,YUMIKO,
	ARTEMIS,CASPIAN,SIDRA,XULL,KAYA,ISAIAH,JIRO,LIN_FEI,ZARIEL,RAYMAN,DUSK,FAIT,THOR,PETRA,VECTOR,VOLKOV,ONYX,JAYEUN,MAKO

}
